config/routes.rb
Rails.application.routes.draw do
  root 'top#index'
  get 'login', to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  post '/guest_login', to: 'sessions#guest_login'
  get 'sessions/new'
  get "signup" => "users#new"
  post "users/create" => "users#create"
  get 'users/create'
  get "users/:id" => "users#show"
  get 'posts/index'
  get 'posts/create'
  get 'top/index'
  get 'reviews/post/:id' => "reviews#post"
  get 'shops/index'
  resources :shops
  resources :reviews
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/prefecture.rb
class Prefecture < ApplicationRecord
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :shop
end

app/models/shop.rb
class Shop < ApplicationRecord
  has_many :reviews
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper

  private
  # ログイン済みユーザーかどうか確認
  def logged_in_user
    unless logged_in?
      redirect_to login_url
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
  end

  def create
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def post
    @shop = Shop.find_by(id: params[:id])
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)
    @review.save
    redirect_to shop_path(@review.shop)
  end

  private
    def review_params
      params.require(:review).permit(:shop_id, :body, :next_seat_distance, :measures_staff, :private_room, :disinfection, :mask_customer, :mask_staff)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      log_in user
      redirect_to root_url
    else
      render 'new'
    end
  end

  def guest_login
    user = User.find_or_create_by!(email: 'guest@example.com') do |user|
      user.password = SecureRandom.urlsafe_base64
      # user.confirmed_at = Time.now  # Confirmable を使用している場合は必要
      # 例えば name を入力必須としているならば， user.name = "ゲスト" なども必要
    end
    log_in user
    redirect_to root_path, notice: 'ゲストユーザーとしてログインしました。'
  end

  def destroy
    log_out if logged_in?
    redirect_to root_url
  end
end

app/controllers/shops_controller.rb
class ShopsController < ApplicationController
  def show
    @shop = Shop.find_by(id: params[:id])
    @review = Review.new
    @reviews = @shop.reviews
  end

  def index
    @shops = Shop.all
  end
end

app/controllers/top_controller.rb
class TopController < ApplicationController
  def index
    @shops = Shop.all
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
    @prefecture = Prefecture.all
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to("/")
    else
      render 'new'
    end
  end

  def show
    @user = User.find_by(id: params[:id])
  end

  private
    def user_params
      params.require(:user).permit(:name, :email, :prefecture, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  # 渡されたユーザーでログインする
  def log_in(user)
    session[:user_id] = user.id
  end

  # 現在ログイン中のユーザーを返す（いる場合）
  def current_user
    if session[:user_id]
      @current_user ||=User.find_by(id: session[:user_id])
    end
  end

  # 受け取ったユーザーがログイン中のユーザーと一致すればtrueを返す
  def current_user?(user)
    user == current_user
  end

  # ユーザーがログインしていればtrue、その他ならfalseを返す
  def logged_in?
    !current_user.nil?
  end

  # 現在のユーザーをログアウトする
  def log_out
    session.delete(:user_id)
    @current_user = nil
  end
end

app/helpers/shop_helper.rb
module ShopHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>App</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
    <%= javascript_include_tag 'application' %>
    <%= stylesheet_pack_tag 'application' %>

    <script src="https://code.jquery.com/jquery-2.2.4.js" integrity="sha256-iT6Q9iMJYuQiMWNd9lDyBUStIq/8PuOW33aOqmvFpqI=" crossorigin="anonymous"></script>

    <!-- スマホナビの表示・非表示 -->
    <script>
      $(function() {
        const hum = $('#hamburger, .close')
        const nav = $('.sp-nav')
        hum.on('click', function(){
           nav.toggleClass('toggle');
        });
      });
    </script>
  </head>

  <body>
    <header>
      <nav class="pc-nav">
        <ul>
          <% if !logged_in? %>
            <li><%= link_to "新規登録", "/signup", { class: "link"} %></li>
            <li><%= link_to "ログイン", "/login", { class: "link"} %></li>
            <li><%= link_to "ゲストログイン", "/guest_login", {method: :post, class: "link"} %></li>
          <% else %>
            <li><%= link_to "ログアウト", "/logout", {method: :delete, class: "link"} %></li>
          <% end %>
          <li><a href="/">トップページ</a></li>
          <li><a href="#">検索</a></li>
          <li><a href="/shops/index">店舗一覧</a></li>
        </ul>
      </nav>
      <nav class="sp-nav">
        <ul>
          <% if !logged_in? %>
            <li><%= link_to "新規登録", "/signup", { class: "link"} %></li>
            <li><%= link_to "ログイン", "/login", { class: "link"} %></li>
            <li><%= link_to "ゲストログイン", "/guest_login", {method: :post, class: "link"} %></li>
          <% else %>
            <li><%= link_to "ログアウト", "/logout", {method: :delete, class: "link"} %></li>
          <% end %>
          <li><a href="/">トップページ</a></li>
          <li><a href="#">検索</a></li>
          <li><a href="/shops/index">店舗一覧</a></li>
          <li class="close"><span>閉じる</span></li>
        </ul>
      </nav>
      <div id="hamburger">
         <span></span>
      </div>
    </header>
    <main>
      <%= yield %>
    </main>
  </body>
</html>

app/views/posts/create.html.erb
<h1>Posts#create</h1>
<p>Find me in app/views/posts/create.html.erb</p>

app/views/posts/index.html.erb
<h1>Posts#index</h1>
<p>Find me in app/views/posts/index.html.erb</p>

app/views/reviews/post.html.erb
<%= stylesheet_link_tag "reviews", :media => "all" %>
<div class="main-wrapper">
  <div class="post">
    <%= form_for @review do |f| %>
      <div class="shop-name">
        <label><%= @shop.name %></label>
        <%= f.hidden_field :shop_id, value: @shop.id %>
      </div>
      <div id="private_room">
        <label>個室</label>
        <%= f.radio_button :private_room, :true %>
        <%= f.label :private_room_true, "あり" %>
        <%= f.radio_button :private_room, :false %>
        <%= f.label :private_room_false, "なし" %>
      </div>
      <div id="star_next_seat_distance">
        <%= f.label :next_seat_distance,'隣席との距離 ' %>
      </div>
      <div id="disinfection">
        <label>アルコール消毒</label>
        <%= f.radio_button :disinfection, :true %>
        <%= f.label :disinfection_true, "あり" %>
        <%= f.radio_button :disinfection, :false %>
        <%= f.label :disinfection_false, "なし" %>
      </div>
      <div id="mask_customer">
        <label>顧客マスク着用</label>
        <%= f.radio_button :mask_customer, :true %>
        <%= f.label :mask_customer_true, "あり" %>
        <%= f.radio_button :mask_customer, :false %>
        <%= f.label :mask_customer_false, "なし" %>
      </div>
      <div id="mask_staff">
        <label>従業員マスク着用</label>
        <%= f.radio_button :mask_staff, :true %>
        <%= f.label :mask_staff_true, "あり" %>
        <%= f.radio_button :mask_staff, :false %>
        <%= f.label :mask_staff_false, "なし" %>
      </div>
      <div id="star_measures_staff">
        <%= f.label :measures_staff,'従業員の感染症対策 ' %>
      </div>
      <div id="body">
        <%= f.text_field :body, class: "text-field", :size=>"30x30" %>
      </div>
      <%= f.submit '投稿', class: "submit-btn" %>
    <% end %>
    
      <!-- 評価javascript -->
      <script>
      $('#star_next_seat_distance').raty({
        size   : 36,
        starOff:  '<%= asset_path('star-off.png') %>',
        starOn : '<%= asset_path('star-on.png') %>',
        starHalf: '<%= asset_path('star-half.png') %>',
        scoreName: 'review[next_seat_distance]',
        half: true,
      });
      </script>  
    
      <!-- 評価javascript -->
      <script>
      $('#star_measures_staff').raty({
        size   : 36,
        starOff:  '<%= asset_path('star-off.png') %>',
        starOn : '<%= asset_path('star-on.png') %>',
        starHalf: '<%= asset_path('star-half.png') %>',
        scoreName: 'review[measures_staff]',
        half: true,
      });
    </script>
  </div>
</div>

app/views/shops/index.html.erb
<%= stylesheet_link_tag "shop", :media => "all" %>
<div class="main-wrapper">
  <div class="shops">
    <% @shops.each do |shop| %>
      <div class="shop border-class">
        <div class="shop-name border-bottom-class">
          <%= shop.name %>
        </div>
        <div class="shop-image border-bottom-class">
          <%= image_tag "#{shop.image_name}", class: "image" %>
        </div>
        <div class="shop-info border-bottom-class">
          <ul>
            <li><label>　　住所　:　</label><%= shop.location %></li>
            <li><label>　　種別　:　</label><%= shop.genre %></li>
            <li><label>　　価格　:　</label><%= shop.price %></li>
            <li><label>営業時間　:　</label><%= shop.opening_hours %></li>
            <li>
              <% if shop.private_room %>
                <p>　　個室　:　あり</p>
              <% else %>
                <p>　　個室　:　なし</p>
              <% end %>
            </li>
          </ul>
        </div>
        <div class="shop-link border-bottom-class">
          <%= link_to("店舗情報", "/shops/#{shop.id}", {class: "link"}) %>
          <%= link_to("クチコミ投稿", "/reviews/post/#{shop.id}", {class: "link"}) %>
        </div>
        <div class="shop-intro">
          <%= shop.introduction %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/shops/show.html.erb
<%= stylesheet_link_tag "shop", :media => "all" %>
<div class="main-wrapper">
  <div class="reviews">
    <% @reviews.each do |r| %>
      <div class="review border-class">
        <div class="shop-name border-bottom-class">
          <%= @shop.name %>
        </div>
        <div class="shop-info border-bottom-class">
          <div id="private_room_<%= r.id %>">
            <label>個室</label>
            <% if r.private_room %>
              <label>あり</label>
            <% else %>
              <label>なし</label>
            <% end %>
          </div>
          <div id="star_rate_next_seat_distance_<%= r.id %>">
            <label>隣席との距離</label>
          </div>
          <div id="disinfection_<%= r.id %>">
            <label>アルコール消毒</label>
            <% if r.disinfection %>
              <label>あり</label>
            <% else %>
              <label>なし</label>
            <% end %>
          </div>
          <div id="mask_staff_<%= r.id %>">
            <label>顧客マスク着用</label>
            <% if r.mask_staff %>
              <label>あり</label>
            <% else %>
              <label>なし</label>
            <% end %>
          </div>
          <div id="mask_staff_<%= r.id %>">
            <label>従業員マスク着用</label>
            <% if r.mask_staff %>
              <label>あり</label>
            <% else %>
              <label>なし</label>
            <% end %>
          </div>
          <div id="star_rate_measures_staff<%= r.id %>">
            <label>感染症対策</label>
          </div>
        </div>
        <div class="review-body">
          <%= r.body %>
          <script>
            $('#star_rate_next_seat_distance_<%=r.id%>').raty({
              size      : 36,
              starOff   : '<%= asset_path('star-off.png') %>',
              starOn    : '<%= asset_path('star-on.png') %>',
              starHalf: '<%= asset_path('star-half.png') %>',
              half      : true,
              readOnly: true,
              score: <%= r.next_seat_distance %>,
            });
          </script>
          <script>
            $('#star_rate_measures_staff<%=r.id%>').raty({
              size      : 36,
              starOff   : '<%= asset_path('star-off.png') %>',
              starOn    : '<%= asset_path('star-on.png') %>',
              starHalf: '<%= asset_path('star-half.png') %>',
              half      : true,
              readOnly: true,
              score: <%= r.measures_staff %>,
            });
          </script>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/top/index.html.erb
<%= stylesheet_link_tag "shop", :media => "all" %>
<div class="main-wrapper">
  <div class="shops">
    <% @shops.each do |shop| %>
      <div class="shop border-class">
        <div class="shop-name border-bottom-class">
          <%= shop.name %>
        </div>
        <div class="shop-image border-bottom-class">
          <%= image_tag "#{shop.image_name}", class: "image" %>
        </div>
        <div class="shop-info border-bottom-class">
          <ul>
            <li><label>　　住所　:　</label><%= shop.location %></li>
            <li><label>　　種別　:　</label><%= shop.genre %></li>
            <li><label>　　価格　:　</label><%= shop.price %></li>
            <li><label>営業時間　:　</label><%= shop.opening_hours %></li>
            <li>
              <% if shop.private_room %>
                <p>　　個室　:　あり</p>
              <% else %>
                <p>　　個室　:　なし</p>
              <% end %>
            </li>
          </ul>
        </div>
        <div class="shop-link border-bottom-class">
          <%= link_to("店舗情報", "/shops/#{shop.id}", {class: "link"}) %>
          <%= link_to("クチコミ投稿", "/reviews/post/#{shop.id}", {class: "link"}) %>
        </div>
        <div class="shop-intro">
          <%= shop.introduction %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/new.html.erb
<%= stylesheet_link_tag "users", :media => "all" %>
<div class="main-wrapper">
  <% provide(:title, 'Sign up') %>
  <div class="signup">
    <div>
      <%= form_for @user, url: users_create_path do |f| %>
        <%= f.label :name %>
        <%= f.text_field :name %>
    </div>
    <div>
        <%= f.label :email %>
        <%= f.email_field :email %>
    </div>
    <div>
        <%= f.label :prefecture %>
        <%= f.collection_select(:prefecture, @prefecture, :id, :prefecture) %>
    </div>
    <div>
        <%= f.label :password %>
        <%= f.password_field :password %>
    </div>
    <div>
        <%= f.label :password_confirmation, "Confirmation" %>
        <%= f.password_field :password_confirmation %>
    </div>
    <div>
        <%= f.submit "Create my account", class: "btn btn-primary" %>
      <% end %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<%= @user.name %>
<%= @user.email %>